version: '2'
services:
  crawler:
    build: .
    image: spiegel-crawler:1.0
    container_name: "spiegel-crawler"
    ports: ["5000:5000"]
    volumes:
      - ./wait-for-it.sh:/crawler/wait-for-it.sh
    command: bash -c "/crawler/wait-for-it.sh elasticsearch:9201 -t 60 && python app.py"
    networks:
      - default
    depends_on:
      - elasticsearch


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    container_name: "elasticsearch"
    ports: ["9201:9201"]
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    container_name: kibana-spiegel-utils
    ports: ['5602:5602']
    volumes:
      - ./elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on: ['elasticsearch']
    networks:
      - default